### ISSUE TITLE
Feature Request: Two Finger Pinch to Zoom

### ISSUE THREAD

**Issue by TimilsinaBimal** [harshadgavali/gnome-gesture-improvements#101]
The extension is so great. Thank you for this!
But it would have been great if you can add an option for a two-finger pinch to zoom just like in windows. Not like Ctrl+Plus but zoom as in Windows, This will be useful for someone like me who like to zoom the contents in a browser, images, and so on.
Also, It would have been great if there was an option to remove the cyclic nature of three-finger swipe gestures.

**Comment by harshadgavali** [comment]
Sorry 2 finger touchpad events/gestures are only for applications to handle.
Also Firefox on wayland already has built in pinch to zoom.

**Comment by harshadgavali** [comment]
Also option to configure cyclic overview gestures will be added in next version.
https://github.com/harshadgavali/gnome-gesture-improvements/issues/90

**Comment by TimilsinaBimal** [comment]
Is there any way to disable all three-finger gestures? I used `comfortable-swipe` and the animations of that package feel smoother for me. But I really liked the window switcher gesture of your module. So, I wanna mix them both for my workflow. If that is possible.

**Comment by harshadgavali** [comment]
Yes you can disable all 3 finger gestures. For you just turning off “Window manipulation” should be sufficient.

**Comment by harshadgavali** [comment]
Ah you want to disable workspace switching gesture(and possibly overview too).
I didn’t want to provide option for this since this gesture are default in gnome and providing this option might make it difficult to maintain this extension.

but you might be able to disable them though code.
* to disable overview gestures change following to empty array
https://github.com/harshadgavali/gnome-gesture-improvements/blob/448fd763863b90f095b8317e77c9eaa0067bca46/extension/src/overviewRoundTrip.ts#L66
* to disable workspace gestures change following to empty array
https://github.com/harshadgavali/gnome-gesture-improvements/blob/448fd763863b90f095b8317e77c9eaa0067bca46/extension/src/gestures.ts#L87

**Comment by TimilsinaBimal** [comment]
That is exactly what I needed! Thank you so much!
