### ISSUE TITLE
Respect natural scrolling setting from gnome

### ISSUE THREAD

**Issue by Urgau** [harshadgavali/gnome-gesture-improvements#16]
This extension doesn't respect the "natural scrolling" toggle from the Gnome settings.
It would be good to respect that.

**Comment by harshadgavali** [comment]
Can you try [wip/pref/workspace-natural-scroll](https://github.com/harshadgavali/gnome-gesture-improvements/tree/wip/pref/workspace-natural-scroll) branch?

I'm considering it as wip, because preference option might change when I need to redesign preference window (https://github.com/harshadgavali/gnome-gesture-improvements/issues/13) 

### Install
```
git clone https://github.com/harshadgavali/gnome-gesture-improvements.git/
cd gnome-gesture-improvements
git checkout wip/pref/workspace-natural-scroll
npm install
npm run update
```

### Change preference
```
# first change directory to extension folder
cd ~/.local/share/gnome-shell/extensions/gestureImprovements@gestures/

# to disable natural scroll
gsettings --schemadir schemas/ set org.gnome.shell.extensions.gestureImprovements follow-natural-scroll false

# to enable natural scroll
gsettings --schemadir schemas/ set org.gnome.shell.extensions.gestureImprovements follow-natural-scroll false
```
