### ISSUE TITLE
Show Desktop with 3 finger down gesture

### ISSUE THREAD

**Issue by andreee94** [harshadgavali/gnome-gesture-improvements#6]
The 3 finger down gesture when the focused window is not maximized could be used to show the desktop.
Up to now the gesture shows a transparent red box doing nothing.

Instead when the current window is already maximized the 3 finger up gesture could show the overview.

And in the same way when the desktop is shown, the 3 finger gesture could bring back the latest focused application or it could show the overview (maybe the former with the up gesture and the latter with the down gesture).

**Comment by harshadgavali** [comment]
3 finger down is used to _trigger_ window half-tiling (tile left/right) gesture.
> transparent red box
Are you using theme or because on triggering window half-tile gestsure, blue box is shown on window.
And when you move finger to left/right focused window get's tiled.

For showing overview/appgrid you can try 4-fingers gesture.
And if you like there's option in preferences to use 3-fingers gesture for overview/appgrid and 4-fingers gesture to maximize/half-tile a window.

**Comment by kyteinsky** [comment]
Hey @harshadgavali, I want to implement this feature.
It would be very nice if you provided some pointers on how I should do it and which files I should touch to get the job done.

Thanks.

**Comment by harshadgavali** [comment]
Hey @kyteinsky , thanks!!!!
I have changed code of Swipetracker to work with 4 directions/instead of just 2 (it's in dev branch).
It doesn't provide velocity of swipe yet and
It has some issues Xwayland windows on multimonitor setup, so haven't merged it yet.

Way to implement this would be to 
1. Create SubExtension under 'extension/src/' like 'altTab.ts' (but in dev branch, which is still incomplete)
2. Create swipeTracker and bind begin,update and end events to listen for them https://github.com/harshadgavali/gnome-gesture-improvements/blob/f83f60f2ad25be864ab8e3bd19e84e88789ec49c/extension/src/altTab.ts#L282-L288
3. Implement minimize and unminimize all windows ([gnome-shell code for reference](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/windowManager.js#L589-590))

**Comment by kyteinsky** [comment]
Thanks @harshadgavali for the detailed explanation. I will start working on this now and ask here if I'm stuck.

**Comment by harshadgavali** [comment]
@andreee94 
Show desktop gesture was implemented with 3 finger pinch gesture in recent version.
I hope this resolves this.
