### ISSUE TITLE
Feature: Better Support for PopOS

### ISSUE THREAD

**Issue by mijorus** [harshadgavali/gnome-gesture-improvements#81]
Hi there,
I'm on PopOS 22.04 which has kept the vertical workspace design.
I can switch workspace with 4 fingers up-down. 

My suggestion would be to disable all the setting  related to  4 fingers up/down movements and "3-fingers up to open overview" as well, as Pop uses its own app launcher grid thing

**Comment by harshadgavali** [comment]
Sorry @mijorus.

Since PopOS is moving away from GNOME, extensions won't work at all in their upcoming DE.
So I don't want spend time adding temporary workarounds for their customizations.

**Comment by mijorus** [comment]
I totally understand your position @harshadgavali, so I forking this extension so that I can make it more compatible with Pop.

Could you please explain me roughly how it work?

I can see that most of the action takes place [here](https://github.com/harshadgavali/gnome-gesture-improvements/blob/a31e733b9925f66a0eaf0654d2a505ce3481d5a2/extension/src/gestures.ts#L136), where you connect some gestures with the `apply()` method.

Am I correct?

Thanks  for your time

**Comment by harshadgavali** [comment]
Hi @mijorus, gesture in gestures.ts are related to workspace.

If you just want to disable gesture to navigate app-grid, I think following change might work for you.
I tested following change on Fedora Silverblue 36 RC. It makes so that using 4 finger up/down we can only move between desktop and overview.
```
diff --git a/extension/src/overviewRoundTrip.ts b/extension/src/overviewRoundTrip.ts
index c68120a..8a13d76 100644
--- a/extension/src/overviewRoundTrip.ts
+++ b/extension/src/overviewRoundTrip.ts
@@ -99,8 +99,7 @@ export class OverviewRoundTripGestureExtension implements ISubExtension {
 	_gestureBegin(tracker: typeof SwipeTracker.prototype): void {
 		const _tracker = {
 			confirmSwipe: (distance: number, snapPoints: number[], currentProgress: number, cancelProgress: number) => {
-				snapPoints.unshift(OverviewControlsState.APP_GRID_P);
-				snapPoints.push(OverviewControlsState.HIDDEN_N);
+				snapPoints.pop();
 				tracker.confirmSwipe(
 					distance,
 					snapPoints,
```


But if you want something else for overview gesture. You might need to update this file (extension/src/overviewRoundTrip.ts).

PS: In case you missed there's also [touchegg](https://github.com/JoseExposito/touchegg). that can work on non-GNOME environments.

**Comment by mijorus** [comment]
Thank you for  the explanation.

Touchegg is not needed  anymore, as I can use Wayland on PopOS.

Pop is still using GNOME and will problably keep using it until next year (or more, I bet that COSMIC will be postponed).
