### ISSUE TITLE
Some options are missing?

### ISSUE THREAD

**Issue by 097115** [harshadgavali/gnome-gesture-improvements#89]
Ubuntu 21.10, X. I did installed the daemon (via `sh install.sh --restart`, `systemctl --user status gesture_improvements_gesture_daemon.service` reported it as Active), then installed the extension. And this is the settings window that I get: https://i.imgur.com/ULBlDNI.png

Seems like the app gesture tab is missing, no? Or is it me, who's missing something? :)

**Comment by harshadgavali** [comment]
Hi @097115, yes app gesture are not available for GNOME 40 (version in Ubuntu 21.10).
Most of the change for this feature was in preference window and since GNOME 42 provides libadwaita library for preferences and GNOME 40 doesn't, I decided to have this feature for GNOME 42+ (Which is available for Ubuntu 22.04).
